name: python CI

on:
- pull_request

jobs:
  tox_test:
    name: Run tox (${{ matrix.python_version }})
    strategy:
      matrix:
        python_version:
        - 2.7
        - 3.6
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python_version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python_version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox

    - name: Run tox tests
      run: tox

    - name: Deploy to GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: gh-pages
        python-version: 3.6
        keep_history: true
        build_dir: docs/build/html/.
      env:
        GITHUB_TOKEN: ${{ secrets.ONEVIEW_DEPLOY_TOKEN }}

    - name: coveralls
      uses: AndreMiras/coveralls-python-action@develop
      with:
        github-token: ${{ secrets.COVERALLS_TOKEN }}
        parallel: true
        flag-name: 'Unit Test'
        debug: true

  coveralls_finish:
    needs: tox_test
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel-finished: true
        debug: true
